package Model;

/**
 * This class creates customer objects, which are used to populate the
 * customerList ObservableList object, which is used to populate the
 * customers tableview.
 *
 * @author Joseph Lawter
 */
public class Customer {
    private Integer customerID;
    private String firstName;
    private String lastName;
    private String address;
    private String postalCode;
    private String phoneNumber;
    private String city;
    private String state;
    private String country;

    public Customer(int customerID, String firstName, String lastName,
                    String address, String state, String country, String phoneNumber,
                    String postalCode){
        this.customerID = customerID;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.state = state;
        this.country = country;
        this.phoneNumber = phoneNumber;
        this.postalCode = postalCode;


    }

    /*
    Setter Methods
     */
    /**
     * @param name the customer's first name.
     */
    public void setFirstName(String name){
        this.firstName = name;
    }

    /**
     * @param name the customer's last name.
     */
    public void setLastName(String name){
        this.lastName = name;
    }

    /**
     * @param address the customer's street address
     */
    public void setAddress(String address){
        this.address = address;
    }

    /**
     * @param postal_code the customer's postal code
     */
    public void setPostalCode(String postal_code){
        this.postalCode = postal_code;
    }

    /**
     * @param phone_number the customer's phone number, including the area code.
     */
    public void setPhoneNumber(String phone_number){
        this.phoneNumber = phone_number;
    }

    /**
     * @param customerID the id number of the customer. Note: id numbers are
     *           auto-generated by the program.
     */
    public void setCustomerID(Integer customerID){
        this.customerID = customerID;
    }

    /**
     * @param city the city where the customer resides.
     */
    public void setCity(String city){
        this.city = city;
    }

    /**
     * @param country the country where the customer resides.
     */
    public void setCountry(String country){
        this.country = country;
    }

    /**
     *
     * @param state the first level division of the customer (state is a convenient shorthand).
     */
    public void setState(String state){
        this.state = state;
    }

    /*
    Getter Methods
     */
    /**
     * @return the first name of the customer.
     */
    public String getFirstName(){
        return this.firstName;
    }

    /**
     *
     * @return the last name of the customer.
     */
    public String getLastName(){
        return this.lastName;
    }

    /**
     *
     * @return the street address of the customer.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     *
     * @return the postal code of the customer.
     */
    public String getPostalCode() {
        return this.postalCode;
    }

    /**
     *
     * @return the customer's phone number, including the area code.
     */
    public String getPhoneNumber(){
        return this.phoneNumber;
    }

    /**
     *
     * @return The id number of the customer. Note: id numbers are
     * auto-generated by the program.
     */
    public Integer getCustomerID() {
        return this.customerID;
    }

    /**
     *
     * @return the city where the customer resides.
     */
    public String getCity() {
        return this.city;
    }

    /**
     *
     * @return the country where the customer resides.
     */
    public String getCountry(){
        return this.country;
    }

    /**
     *
     * @return the customer's first level division (state is just a convenient shorthand).
     */
    public String getState(){
        return this.state;
    }
}
